# Config to define all available collections of histograms
# Previously defined collections can be imported with '<<' or '*'
# Any nested collections created by "<<" or '*' operations will be flattened in sidm_processor.py


pv_base: &pv_base
  - "pv_n"
  - "pv_ndof"
  - "pv_z"
  - "pv_rho"
  
electron_base: &electron_base
  - "electron_n"
  - "electron_pt"
  - "electron_eta_phi"

photon_base: &photon_base
  - "photon_n"
  - "photon_pt"
  - "photon_eta_phi"

muon_base: &muon_base
  - "muon_n"
  - "muon_pt"
  - "muon_eta_phi"
  - "muon_absD0"
  - "muon_absD0_lowRange"

dsaMuon_base: &dsaMuon_base
  - "dsaMuon_n"
  - "dsaMuon_pt"
  - "dsaMuon_eta_phi"
  - "dsaMuon_absD0"
  - "dsaMuon_absD0_lowRange"

lj_base: &lj_base
  - "lj_n"
  - "lj_pt"
  - "egm_lj_pt"
  - "mu_lj_pt"
  - "lj0_pt"
  - "lj1_pt"
  - "lj0_e"
  - "lj1_e"
  - "lj0_dRSpread"
  - "lj1_dRSpread"
  - "lj_eta_phi"
  - "lj_electronN"
  - "lj_photonN"
  - "lj_electronPhotonN"
  - "lj_muonN"

lj_isolation: &lj_isolation
  - "lj_pfIsolation05"
  - "lj0_pfIsolation05"
  - "lj1_pfIsolation05"
  - "lj_pfIsolationPtNoPU05"
  - "lj_pfIsolationPt05"
  - "lj_pfIsolation07"
  - "lj_pfIsolationPtNoPU07"
  - "lj_pfIsolationPt07"
  - "lj_pfiso"

ljsource_base: &ljsource_base
  - "ljsource_n"
  - "ljsource_pt"
  - "ljsource_eta_phi"
  - "ljsource_charge"
  - "ljsource_type"

electron_lj_base: &electron_lj_base
  - "electron_lj_dR"
  - "electron_lj_dR_lowRange"

photon_lj_base: &photon_lj_base
  - "photon_lj_dR"
  - "photon_lj_dR_lowRange"
  - "photon_lj_dR_reallyLowRange"

muon_lj_base: &muon_lj_base
  - "muon_lj_dR"
  - "muon_lj_dR_lowRange"

dsaMuon_lj_base: &dsaMuon_lj_base
  - "dsaMuon_lj_dR"
  - "dsaMuon_lj_dR_lowRange"

lj_lj_base: &lj_lj_base
  - "lj_lj_absdphi"
  - "lj_lj_invmass"
  - "lj_lj_invmass_lowRange"

abcd_base: &abcd_base
  - "abcd_lj_lj_dphi_vs_lj0_pfIsolationPt05"

gen_base: &gen_base
  - "gen_abspid"
  - "genE_pt"
  - "genE_pt_highRange"
  - "genE0_pt"
  - "genE1_pt"
  - "genE0_pt_highRange"
  - "genE1_pt_highRange"
  - "genE_genE_dR"
  - "genE_genE_pt"
  - "genMu_pt"
  - "genMu_pt_highRange"
  - "genMu0_pt"
  - "genMu1_pt"
  - "genMu0_pt_highRange"
  - "genMu1_pt_highRange"
  - "genMu_genMu_dR"
  - "genMu_genMu_pt"
  - "genA_pt"
  - "genA_n"
  - "genA_lxy"
  - "genAs_toMu_lxy"
  - "genAs_toE_lxy"
  - "genAs_toMu_n"
  - "genA_pt_highRange"
  - "genA_pt_lxy"
  - "genA_eta_phi"
  - "genA_lj_dR"
  - "genA_lj_dR_lowRange"
  - "genA_genA_dphi"
  - "lj_genA_ptRatio"
  - "egm_lj_genA_ptRatio"
  - "mu_lj_genA_ptRatio"
  - "genA_matched_lj_lxy"
  - "genA_matched_lj_pt"
  - "genA_toMu_matched_lj_lxy"
  - "genA_toE_matched_lj_lxy"
  - "genA_matched_muLj_lxy"
  - "genA_toMu_matched_muLj_lxy"
  - "genA_toMu_matched_muLj_pt"
  - "genA_matched_egmLj_lxy"
  - "genA_toE_matched_egmLj_lxy"
  - "genA_toE_matched_egmLj_pt"
  - "genA_matched_lj_n"

base: &base
  - *pv_base
  - *electron_base
  - *photon_base
  - *muon_base
  - *dsaMuon_base
  - *lj_base
  - *ljsource_base
  - *electron_lj_base
  - *photon_lj_base
  - *muon_lj_base
  - *dsaMuon_lj_base
  - *lj_lj_base
  - *lj_isolation
  - *abcd_base

base_plus_gen: &base_plus_gen
  - *base
  - *gen_base