# Config to define all available selections
# Selections contain object- and event-level cuts
# Previously defined selections can be imported with '<<' or '*'
# Any nested collections created by "<<" or '*' operations will be flattened in sidm_processor.py


# Cuts to apply to objects that are clustered into lepton jets
ljsource_cuts: &ljsource_cuts
    obj_cuts: &obj_ljsource_cuts
      electrons: 
        - "pT > 10 GeV"
        - "|eta| < 2.4"
        - "looseID"
      muons: 
        - "looseID"
        - "pT > 5 GeV"
        - "|eta| < 2.4"
      photons:
        - "pT > 20 GeV"
        - "|eta| < 2.5"
        - "looseID"
      dsamuons: 
        - "pT > 10 GeV"
        - "|eta| < 2.4"
        - "ifcsczero"
        - "segOverlap < 0.66"
        - "extrapolatedDr > 0.2" 
        - "isSubsetAnyPFMuon False"
        - "normChi2 < 4"
        - "DT + CSC hits > 12"
        - "DT + CSC stations >= 2"
        - "ptErrorOverPT < 1"

# basic analysis selections
baseNoLj: &baseNoLj
  obj_cuts: &obj_baseNoLj
    << : *obj_ljsource_cuts
    pvs: &pv_baseNoLj
      - "ndof > 4"
      - "|z| < 24 cm"
      - "|rho| < 0.2 mm"
  evt_cuts: &evt_baseNoLj
    - "PV filter"
    - "Cosmic veto"

base: &base
  obj_cuts: &obj_base
    <<: *obj_baseNoLj
    ljs: &lj_base
      - "pT > 30 GeV"
      - "|eta| < 2.4"
  evt_cuts: &evt_base
    - *evt_baseNoLj
    - ">=2 LJs"
    
4mu: &4mu
  <<: *base
  evt_cuts: &evt_4mu
    - *evt_base
    - "4mu"

2mu2e: &2mu2e
  <<: *base
  evt_cuts: &evt_2mu2e
    - *evt_base
    - "2mu2e"

# basic analysis selections with LJ-A dR matching
matchedLj: &matchedLj
  obj_cuts: &obj_matchedLj
    <<: *obj_base
    ljs: 
      - *lj_base
      - "dR(LJ, A) < 0.2"
  evt_cuts: &evt_matchedLj
    - *evt_base
    - ">=2 matched As"

4mu_matchedLj: &4mu_matchedLj
  <<: *matchedLj
  evt_cuts: &evt_4mu_matchedLj
    - *evt_matchedLj
    - "4mu"

2mu2e_matchedLj: &2mu2e_matchedLj
  <<: *matchedLj
  evt_cuts: &evt_2mu2e_matchedLj
    - *evt_matchedLj
    - "2mu2e"

# basic selections with cuts on A properties and no LJ cuts
baseNoLj_promptA: &baseNoLj_promptA
  <<: *baseNoLj
  obj_cuts:
    <<: *obj_baseNoLj
    genAs:
      - "lxy < 10 cm"
    genAs_toE:
      - "lxy < 10 cm"
    genAs_toMu:
      - "lxy < 10 cm"

baseNoLj_displacedA: &baseNoLj_displacedA
  <<: *baseNoLj
  obj_cuts:
    <<: *obj_baseNoLj
    genAs:
      - "10 cm <= lxy < 100 cm"
    genAs_toE:
      - "10 cm <= lxy < 100 cm"
    genAs_toMu:
      - "10 cm <= lxy < 100 cm"

baseNoLj_veryDisplacedA: &baseNoLj_veryDisplacedA
  <<: *baseNoLj
  obj_cuts:
    <<: *obj_baseNoLj
    genAs:
      - "lxy >= 100 cm"
    genAs_toE:
      - "lxy >= 100 cm"
    genAs_toMu:
      - "lxy >= 100 cm"

baseNoLj_lowLxyA: &baseNoLj_lowLxyA
  <<: *baseNoLj
  obj_cuts:
    <<: *obj_baseNoLj
    genAs:
      - "lxy <= 150 cm"
    genAs_toE:
      - "lxy <= 150 cm"
    genAs_toMu:
      - "lxy <= 150 cm"
      
baseNoLj_highPtA: &baseNoLj_highPtA
  <<: *baseNoLj
  obj_cuts:
    <<: *obj_baseNoLj
    genAs:
      - "pT > 30 GeV"
    genAs_toE:
      - "pT > 30 GeV"
    genAs_toMu:
      - "pT > 30 GeV"

baseNoLj_eLj: &baseNoLj_eLj
  <<: *baseNoLj
  obj_cuts:
    <<: *obj_baseNoLj
    "ljs":
      - "eLj"

baseNoLj_gLj: &baseNoLj_gLj
  <<: *baseNoLj
  obj_cuts:
    <<: *obj_baseNoLj
    "ljs":
      - "gLj"